### PR TITLE
Update PCall implementation in compiler proper to match paper

### PR DESCRIPTION
**Pull request by MatthewFluet**

### CODE REVIEW

**Comment by shwestrick** [comment]
@MatthewFluet sorry I forgot about this and just came back to it now! 

I can't remember, did we test this update already? Or should I run it through the benchmark suite to double check that everything is good before merging?

**Comment by MatthewFluet** [comment]
@shwestrick I probably tested just on a few simple programs.  Would be a good idea to make sure that the benchmarks work out the same.

**Comment by shwestrick** [comment]
Sounds good! Will do after the PLDI submission deadline. I'm hoping to merge all of this into MPL mainline before POPL :)

**Comment by shwestrick** [comment]
Was just doing some testing with this. I was able to run almost all of the benchmarks, and the performance looks similar.

I got a segfault on `nearest-nbrs`; a little debugging and I get the following `Machine.typeCheck` error:
```
swestric aware ~/proj/parallel-ml-bench-hb/mpl (hb)
$ make nearest-nbrs.local-hb-dbg.bin
[INFO] /usr0/home/swestric/proj/mpl/sam-heartbeat/build/bin/mpl -mlb-path-var 'COMPAT mpl-hb' -default-type int64 -default-type word64 -disable-pass splitTypes1 -disable-pass splitTypes2 -detect-entanglement false -debug true -debug-runtime true -keep g -type-check true -mlb-path-var 'GRAINS small' -mlb-path-var 'PICK_FJ greedy-work-amortized' -output bin/nearest-nbrs.local-hb-dbg.bin /usr0/home/swestric/proj/parallel-ml-bench-hb/mpl/bench/nearest-nbrs/nearest-nbrs.mlb

invalid kind: PCallReturn {args = (),
                           frameInfo = {frameOffsets = {index = 538,
                                                        offsets = (24,
                                                                   32,
                                                                   104,
                                                                   128,
                                                                   144,
                                                                   152,
                                                                   176,
                                                                   184,
                                                                   192,
                                                                   200,
                                                                   240)},
                                        index = 426,
                                        kind = PCALL_PARR_FRAME,
                                        size = 280,
                                        sourceSeqIndex = None}}
invalid block: L_6988: {kind = PCallReturn {args = (),
                                            frameInfo = {frameOffsets = {index = 538,
                                                                         offsets = (24,
                                                                                    32,
                                                                                    104,
                                                                                    128,
                                                                                    144,
                                                                                    152,
                                                                                    176,
                                                                                    184,
                                                                                    192,
                                                                                    200,
                                                                                    240)},
                                                         index = 426,
                                                         kind = PCALL_PARR_FRAME,
                                                         size = 280,
                                                         sourceSeqIndex = None}},
                        live = (SP(24): Objptr (opt_16),
                                SP(32): Objptr (opt_87),
                                SP(200): Objptr (opt_71),
                                SP(192): Objptr (opt_47),
                                SP(184): Objptr (opt_72),
                                SP(176): Objptr (opt_28),
                                SP(152): Objptr (opt_37),
                                SP(144): Objptr (opt_27),
                                SP(128): Objptr (opt_38),
                                SP(104): Objptr (opt_85),
                                SP(264): Objptr (opt_134)),
                        raises = Some (),
                        returns = Some (SP(0): Objptr (opt_164, opt_163))}
                 SP(0): Objptr (opt_134) = SP(264): Objptr (opt_134)
                 SP(8): Objptr (opt_28) =
                   OP (SP(128): Objptr (opt_38), 16): Objptr (opt_28)
                 SP(16): Objptr (opt_37) =
                   OP (SP(128): Objptr (opt_38), 8): Objptr (opt_37)
                 SP(40): Objptr (opt_27) =
                   OP (SP(128): Objptr (opt_38), 0): Objptr (opt_27)
                 SW64(216): Label L_6895 = L_6895
                 TQ(70): CPointer = CPointer_add (<StackTop>, 0xE0:w64)
                 OW64 (<GCState>, 40): Word64 =
                   CPointer_diff (TQ(70): CPointer,
                                  OQ (<GCState>, 952): CPointer)
                 SW64(240): Word64 = 0x1:w64
                 SP(248): Objptr (opt_27) = SP(40): Objptr (opt_27)
                 SP(256): Objptr (opt_5) = GP(229): Objptr (opt_5)
                 SP(264): Objptr (opt_37) = SP(16): Objptr (opt_37)
                 SP(272): Objptr (opt_28) = SP(8): Objptr (opt_28)
                 Call {label = x_52,
                       live = (SP(40): Objptr (opt_27),
                               SP(16): Objptr (opt_37),
                               SP(8): Objptr (opt_28),
                               SP(0): Objptr (opt_134),
                               SP(24): Objptr (opt_16),
                               SP(32): Objptr (opt_87),
                               SP(200): Objptr (opt_71),
                               SP(192): Objptr (opt_47),
                               SP(184): Objptr (opt_72),
                               SP(176): Objptr (opt_28),
                               SP(152): Objptr (opt_37),
                               SP(144): Objptr (opt_27),
                               SP(104): Objptr (opt_85),
                               SW64(240): Word64,
                               SP(248): Objptr (opt_27),
                               SP(256): Objptr (opt_5),
                               SP(264): Objptr (opt_37),
                               SP(272): Objptr (opt_28)),
                       return = Some {return = L_10325,
                                      handler = Some L_6895,
                                      size = 240}}
MLton [mpl] 20230701.160408-g439bd78d2-dirty raised: Fail: Machine.typeCheck

[INFO] compilation failed
make: *** [Makefile:17: nearest-nbrs.local-hb-dbg.bin] Error 1
```

**Comment by shwestrick** [comment]
And, I've confirmed that it builds successfully with `-type-check true` before the PR.

By the way, you'll need to pass `-detect-entanglement false` together with `-type-check true`, otherwise there seems to be an unrelated error which is caused by the entanglement detector constructing an object type that is invalid... will need to debug that separately.

**Comment by MatthewFluet** [comment]
I think I found the problem, in `mlton/backend/backend.fun`:
```
@@ -986,13 +986,13 @@ fun toMachine (rssa: Rssa.Program.t) =
                                         else if Label.equals (label, parr)
                                            then M.FrameInfo.Kind.PCALL_PARR_FRAME
                                         else Error.bug "Backend.genFunc.setFrameInfo: PCallReturn"
+                                     (* The size is that of the cont *)
+                                     val size = #size (labelRegInfo cont)
                                      (* The PCall DataPtr slot is also live. *)
                                      val offsets =
                                         if Label.equals (label, parl) orelse Label.equals (label, parr)
                                            then offsets @ [Bytes.- (size, Bytes.+ (Runtime.labelSize (), Runtime.objptrSize ()))]
                                            else offsets
-                                     (* The size is that of the cont *)
-                                     val size = #size (labelRegInfo cont)
                                   in
                                      (true, kind, offsets, size)
                                   end
```
The offset of the PCall DataPtr was being calculated relative to the minimum size of the `parr` frame (i.e., the size that accommodates all of the stack slots live down the `parr` continuation), but it should be calculated relative to the actual size of the `parr` frame (which will be equal to the size of the "normal" `cont` continuation, since the `cont` continuation's size accommodates all of the stack slots live down all of `cont`, `parl`, and `parr` continuations).  I'm double checking this now, but assuming that fixes it, then I'll force push to my branch, since it's a bug in the last commit.

**Comment by MatthewFluet** [comment]
The fixed size seems to have worked:
```
$ ./bench/nearest-nbrs/nearest-nbrs 
J DEBUGGING
generated input in 0.2158s
warmup 0.0000
repeat 1
running nearest neighbors
built quadtree in 0.8703s
found all neighbors in 0.7777s
time 1.6481s

average 1.6481s
total   1.6481s
end-to-end 1.6481s
======== Runtime Stats ========
num spawns        7695
  eager           4897 (64%)
  at heartbeat    2798 (36%)

num heartbeats    2928
  skipped         1624 (55%)

spawns / hb       2.63
  eager           1.67
  at heartbeat    0.96

num steals        0

max hb stack walk 33
max hb stack size 5976
====== End Runtime Stats ======
result [683809, 132618, 587294, 745694, 922659, 162597, 110420, 28958, 334309, 357074, 943116, ..., 457104]
to see output, use -output and -resolution arguments
for example: nn -N 10000 -output result.ppm -resolution 1000
```

I guess what is surprising is how rarely the "natural" sizes of the `cont`, `parl`, and `parr` continuations differ.

Though, maybe not terribly surprising; just before the `pcall`, there is a `val (inject, project) = Universal.embed ()`, where the `inject` is live in both `leftSideParCont` and `rightSide`.  Since it is the most recent live variable, it probably lives highest in the stack frame, so probably often establishes the "natural" sizes of the `parl` and `parr`.

**Comment by shwestrick** [comment]
Excellent! I'll run it through the benchmark suite.

**Comment by shwestrick** [comment]
All the benchmarks are looking good. Thanks Matthew!

**Pull request merged**
